<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net4.0</TargetFramework>
    <RootNamespace>mobile_eggbert_fna</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DefineConstants>FNA</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineConstants>KFNA</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Include="FNADllMap.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
    <ItemGroup>
    <ProjectReference Include="../FNA/FNA.Core.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

</Project>
